### ISSUE TITLE
Beautify Demo (GH-Pages)

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#18]
The current demo/gh-pages documentation is an unstyled plain text page. It would be nice to make this more attractive. You can see what it looks like today here: https://intuit.github.io/LD-React-Components/

**Comment by CharaeKeow** [comment]
Hi. Would love to work on this.

**Comment by poorpaddy** [comment]
@CharaeKeow by all means. It is as simple as creating a PR.

**Comment by ggrumbley** [comment]
@poorpaddy I want to give this a bit more oomf. Would you be fine with me adding Storybook?

**Comment by poorpaddy** [comment]
@ggrumbley I'm not opposed to it. Would like to see what you have in mind but it might also make the package unnecessarily heavy too.

**Comment by ggrumbley** [comment]
@poorpaddy I got you fam...

**Comment by cueo** [comment]
The Github pages seem to be not working. Might be related to the addition of Storybook.
https://intuit.github.io/LD-React-Components/ gives the error:
>Cannot read property 'undefined' of undefined
<img width="1617" alt="Screenshot 2019-10-07 at 10 13 58 AM" src="https://user-images.githubusercontent.com/13873846/66285631-3a06e600-e8eb-11e9-9963-5aa85d6c82ff.png">

**Comment by poorpaddy** [comment]
Going to divide this issue up by each component/issue since it appears to be abandoned at this point.
