### ISSUE TITLE
Dependency Updates

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#19]
Update all current dependencies and run tests and ensure tests are still passing.

**Comment by zjael** [comment]
Will give a shot. :)

**Comment by poorpaddy** [comment]
@zjael Sounds good. Just fork and create a pull request. Remember to add yourself as a contributor in the PR. See readme for more information on that.

**Comment by poorpaddy** [comment]
Added you as a contributor in the docs.
