### ISSUE TITLE
Refactor for TypeScript: Scaffolding

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#20]
There's a lot of benefit to using TypeScript for collaboration but also for self documenting code. Would be nice to have this project follow suit.

This issue is for setting up the scaffolding to support incremental TS building.

[ ] Backwards compatible
[ ] Tests Pass
[ ] Linting Passes

**Comment by hjaintech** [comment]
Hey @poorpaddy , Can I pick this up ?

**Comment by poorpaddy** [comment]
@hjaintech Yes, by all means. Just fork and create a pull request. Remember to add yourself as a contributor in the PR. See readme for more information on that.

**Comment by hjaintech** [comment]
@poorpaddy Is there some documentation/examples apart from the Readme file which can help me understand the functionality/use case of this project ?

**Comment by poorpaddy** [comment]
This package is essentially an integration to the LaunchDarkly feature flag service. You can get an idea of what it does by visiting their site at https://launchdarkly.com.

As it pertains to documentation of this package all of the documentation is in the readme.

**Comment by poorpaddy** [comment]
@hjaintech I agree incremental is probably best. Although it really isn't a very large package.

**Comment by mathagician** [comment]
@poorpaddy I agree. Can you split it and create more issues. That shall also help in testing also.

**Comment by poorpaddy** [comment]
@mathagician if you have any suggestions on how we should split it up I am open to creating the issues. Would love seeing multiple developers collaborate.

**Comment by Swazimodo** [comment]
I have TS'ed things in the past and would be happy to help out. If this get's split then I can do a chunk. Whoever does the first PR will have to also lay the foundation for TS support (packages and config).

**Comment by poorpaddy** [comment]
@Swazimodo Yes, I am about to create a handful of issues. We can treat this one as a scaffolding.

**Comment by poorpaddy** [comment]
@Swazimodo @mathagician @hjaintech I've creator a bunch of issues around this. Hopefully it makes it a bit easier to contribute.

**Comment by billy-le** [comment]
Hello, I would love to help out. I haven't set up ts in an existing project before so I won't be putting time into getting that up. However, I can handle converting some of the components if someone is able to get TS in the project.

**Comment by heykevin** [comment]
If no one's picked up the task of doing the scaffolding I can also give it a shot. I've introduced TS into projects a handful of times.

**Comment by poorpaddy** [comment]
@Swazimodo While I assigned it, it is on a first mergable pull request basis.

**Comment by Swazimodo** [comment]
Sorry for stealing this one but it was blocking my other change
