### ISSUE TITLE
Troubleshoot CircleCi Failing Status

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#22]
I have a theory. While builds are succeeding and the gh-page's branch is now being correctly skipped. It's old status of failed on the gh-pages branch is being syndicated since it reports the last known status for skipped branches. Just a theory. 

The goal is to once again have a passing status come from CircleCi. It may even require contacting and working with them to fix.

**Comment by Buranch** [comment]
Hi, Would like to work on this issue

**Comment by poorpaddy** [comment]
@Buranch Yes, by all means. Just fork and create a pull request. Remember to add yourself as a contributor in the PR. See readme for more information on that.

**Comment by luminous3** [comment]
I'm looking into this

**Comment by roxiomontes** [comment]
There is no available fix at the moment. Just met with Circle Ci  team and this is an internal bug. They will reach out to me once they are done with the fix.
