### ISSUE TITLE
Fix Contribution Generation

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#23]
**Describe the bug**

Currently this repo utilized `all-contributors-cli` for adding contributors to the readme. At this time it would appear the generator is not working correctly.

**To Reproduce**

1. Clone package and run yarn to install dependencies.
2. Run `yarn contributors:add` to start the process of adding a contributor.
3. Select any option and it should encounter an error.

**Expected behavior**

Able to get thru whole process and contributors are automatically added to the correct place in the readme file.

**Comment by hjaintech** [comment]
@poorpaddy This issue can be closed now.

**Comment by poorpaddy** [comment]
@hjaintech can you provide some details about your environment please? I'm failing to get the command to work correctly. 
<img width="579" alt="Screen Shot 2019-10-01 at 1 16 23 PM" src="https://user-images.githubusercontent.com/2213076/65997204-c9c11600-e44d-11e9-8e33-afe18774b0d7.png">

**Comment by hjaintech** [comment]
@poorpaddy As per the documentation [here](https://allcontributors.org/docs/en/cli/usage#all-contributors-add), you can directly add the contributor in one line in below format

`all-contributors add <username> <contribution>`

For example 

`all-contributors add jfmengels code,doc`
