### ISSUE TITLE
Setup & Configure Linting

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#25]
This repo is coming along nicely in terms of quality control but it can always improve. Perhaps adding some linting will help further improve it. Ideally this repo would be setup using the configuration from https://github.com/paulolramos/eslint-prettier-airbnb-react.

Then of course without modifying a bunch of rules go thru and fix the issues found. Once issues are found we can then add the prettier badge to the readme and feel good about it.

**Comment by ConorGrocock** [comment]
I'd like to take a shot at doing this.

**Comment by poorpaddy** [comment]
@ConorGrocock Yes, by all means. Just fork and create a pull request. Remember to add yourself as a contributor in the PR. See readme for more information on that.

**Comment by ishubhamarora** [comment]
@poorpaddy See if #27 perfectly enhance this open issue. Please let me know your thoughts there.
