### ISSUE TITLE
Refactor for TypeScript: FeatureFlag Component

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#35]
This is one part of a set of issues for refactoring to TypeScript.

Refactor FeatureFlag component to TypeScript (src/lib/FeatureFlag).

[ ] Passes linting
[ ] Unit Tests Pass

**Comment by josediego** [comment]
I'd like to tackle this 🚀

**Comment by josediego** [comment]
Let me know if https://github.com/intuit/LD-React-Components/pull/40 works helps you to achieve this. Thanks

**Comment by poorpaddy** [comment]
Looks good!
