### ISSUE TITLE
Refactor for TypeScript: FeatureSwitch Component

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#36]
This is one part of a set of issues for refactoring to TypeScript.

Refactor FeatureSwitch component to TypeScript (src/lib/FeatureSwitch).

[ ] Passes linting
[ ] Unit Tests Pass

**Comment by Swazimodo** [comment]
I'll take this one

**Comment by Swazimodo** [comment]
@poorpaddy Can you review my PR. It looks like there is an issue with the CI pipeline. It is failing to load packages but I can do it locally without issue. I'm using yarn v1.17.3.

**Comment by Swazimodo** [comment]
I figured out the issue. It is hitting my custom npm repository instead of a public one. I should be able to resolve this.
