### ISSUE TITLE
Refactor for TypeScript: FeatureTrue Component

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#37]
This is one part of a set of issues for refactoring to TypeScript.

Refactor FeatureTrue component to TypeScript (src/lib/FeatureTrue).

[ ] Passes linting
[ ] Unit Tests Pass

**Comment by pramodrhegde** [comment]
Please assign this to me.

**Comment by pramodrhegde** [comment]
@poorpaddy I have raised a PR here #42 

Please review.
