### ISSUE TITLE
Refactor for TypeScript: LaunchDarklyClient

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#38]
This is one part of a set of issues for refactoring to TypeScript.

Refactor LaunchDarklyClient component to TypeScript (src/lib/LaunchDarklyClient).

[ ] Passes linting
[ ] Unit Tests Pass

**Comment by mahboobshah** [comment]
I would like to work on this. :)

**Comment by billy-le** [comment]
I would like to take a shot at this if this is still open.

**Comment by mahboobshah** [comment]
Working on it. Almost done 😊
