### ISSUE TITLE
Fix error in Storybook

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#48]
**Describe the bug**

One of the recent feature enhancements for converting the package to a TypeScript has broken the Storybook documentation.

**To Reproduce**

See gh-pages: 
https://intuit.github.io/LD-React-Components/?path=/story/component-feature-flag--basic-feature-flag

**Expected behavior**

No errors should appear and the component should show.

**Comment by mmissey** [comment]
I'll do this one :D
