### ISSUE TITLE
Client is not typed properly

### ISSUE THREAD

**Issue by Swazimodo** [intuit/LD-React-Components#50]
**Describe the bug**
The client has jsdoc comments but not proper ts types
https://github.com/intuit/LD-React-Components/blob/master/src/lib/LaunchDarklyClient/index.ts

**Comment by Swazimodo** [comment]
@poorpaddy This should be opened up for hacktoberfest

**Comment by Kausam** [comment]
Can I take this up?

**Comment by Kausam** [comment]
@Swazimodo, is this issue about refactoring the client to have more ts syntax?

**Comment by poorpaddy** [comment]
Any luck @Kausam

**Comment by Swazimodo** [comment]
The parameters and results of the functions are not typed.

**Comment by Kausam** [comment]
Okay. I'm on it!
