### ISSUE TITLE
All Contributors Bot

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#51]
**Is your feature request related to a problem? Please describe.**

Currently contributors must manually add themselves as contributors via CLI. Ideally this would be a step that can be skipped if the all-contributors-bot were implemented.

**Describe the solution you'd like**

Implement the all-contributors-bot so that contributors are automatically added to the readme and the all contributors badge count number is updated to correctly reflected.

**Comment by guptaatit94** [comment]
@poorpaddy if I'm reading it correctly, the ask is integrating https://github.com/all-contributors/all-contributors-bot with this repository. If so, I can take it up...

**Comment by poorpaddy** [comment]
@guptaatit94 that is correct.

**Comment by guptaatit94** [comment]
@poorpaddy hi I was working on this and was stuck on the issue where the badge wasn't being updated. I see someone already created a PR. Should I continue working on it?

**Comment by guptaatit94** [comment]
You can check the status of my work here: https://github.com/intuit/LD-React-Components/compare/master...guptaatit94:master

The only reason I didn't have the PR up was because I was trying to get the badges work.
