### ISSUE TITLE
Add remaining components to Storybook

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#52]
Issue #18 replaced the demo/docs with Storybook. However only the first component was added to the new format. Utilizing the old docs which can be found in the link below add the remaining examples to storybook.

old docs: https://intuit.github.io/LD-React-Components/old-docs/

Bonus if you can figure out a means to default storybook to the docs view instead of canvas view.

**Comment by praveenbakkal** [comment]
Can I work on this?

**Comment by poorpaddy** [comment]
@himanshupnt Yes. I have not seen a PR yet.

**Comment by himanshupnt** [comment]
👍

**Comment by himanshupnt** [comment]
@poorpaddy https://github.com/intuit/LD-React-Components/pull/65

**Comment by himanshupnt** [comment]
@all-contributors please add himanshupnt for 💻
