### ISSUE TITLE
Add Test Summary for CircleCi

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#58]
Based on CircleCi's documentation add Test Summaries. See documentation here: https://circleci.com/docs/2.0/configuration-reference/#store_test_results

**Comment by funkadelic** [comment]
@poorpaddy can you assign this to me?

**Comment by t-gok** [comment]
@poorpaddy can I work on this?

**Comment by poorpaddy** [comment]
Yes, first mergeable PR wins. Tomorrow is the last day for Hactoberfest.

**Comment by poorpaddy** [comment]
@funkadelic I don't believe this one is quite finished. Looks like the PR #59 solves the config.yml portion for CircleCi however I don't believe the results from Jest are being output correctly.

**Comment by funkadelic** [comment]
@poorpaddy FYI have follow-up PR + confirmation run in CircleCI https://github.com/intuit/LD-React-Components/pull/62
