### ISSUE TITLE
Resolve Dependencybot Issues

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#84]
**Describe the bug**

There are some notable security issues found in the dependency tree. Please review and resolve them.

**Screenshots**

![Screen Shot 2020-09-10 at 12 10 56 PM](https://user-images.githubusercontent.com/2213076/92788385-c1ac6e80-f35e-11ea-9b02-50c9665998eb.png)

**Comment by ratnamal** [comment]
@poorpaddy  How do i reproduce this? Do some of these issues get resolved with the npm version update?
