### ISSUE TITLE
Update NPM Dependencies

### ISSUE THREAD

**Issue by poorpaddy** [intuit/LD-React-Components#85]
**Is your feature request related to a problem? Please describe.**

Some of the dependencies are out of date and it is crucial for the maintenance of this package to keep up with React and TypeScript. This may mean updating code for compatibility with newer standards.

An easy way to do this is to setup npm-check-updates via `yarn global add npm-check-updates`.
This will provide a list of all dependencies needing to be updated and wether they are major breaking changes or not. 

Example in screenshot below:
![Screen Shot 2020-09-10 at 12 37 43 PM](https://user-images.githubusercontent.com/2213076/92792506-709e7980-f362-11ea-8cfc-16c8089ada69.png)

**Comment by faulker** [comment]
Updated the storybook dependence and updated the storybook configs/stories to work with the update to v6
https://github.com/intuit/LD-React-Components/pull/88

**Comment by nsinghal12** [comment]
@poorpaddy Is this done?

**Comment by poorpaddy** [comment]
@nsinghal12 no it's not. There was a PR for it but it didn't resolve breaking changes that also require code changes and therefore it was rejected.

**Comment by poorpaddy** [comment]
Storybook dependency has been resolved in #88

**Comment by ksuperman** [comment]
@poorpaddy can i take this up as part of the hacktober if not one is working on this ?

**Comment by poorpaddy** [comment]
Hacktoberfest has now concluded and therefore closing this issue specific to October 2020.
